#!/bin/bash
# TODO: remove entry
# TODO: disable IP

IP="127.0.0.1"
HOST_FILE=$(ls ~/bin/etc/hosts)
TMP_FILE="/var/tmp/hosts"

function error()
{
	if [ $# -gt 0 ]
	then
		echo -e "Error: $@"
		echo
	fi

	echo "Usage: $0 add [127.0.0.1] hostname"
	echo "Usage: $0 <pattern>"
	echo "Usage: $0 [edit|-e]"
	echo
	exit
}

function diff_save_exit()
{
	git diff --no-index $HOST_FILE $TMP_FILE
	mv $TMP_FILE $HOST_FILE
	exit
}

function add()
{
	if [ -z "$2" ]
	then
		error
	fi
	if [ -n "$3" ]
	then
		IP="$2"
		HOSTNAME="$3"
	else
		HOSTNAME="$2"
	fi
	
	# check if HOSTNAME exist
	if [ $(grep -i -E "[[:space:]]$HOSTNAME([[:space:]]|$)" $HOST_FILE -c) -gt 0 ]
	then
		error "Hostname exist"\
		"\n\n"$(grep -i -E "[[:space:]]$HOSTNAME([[:space:]]|$)" $HOST_FILE)
	fi
	
	# IP does not exist, add new entry
	if [ $(grep -c $IP $HOST_FILE) -eq 0 ]
	then
		cp $HOST_FILE $TMP_FILE
		echo "$IP $HOSTNAME" >> $TMP_FILE
		diff_save_exit
	fi
	
	# IP exist to append new entry
	_line=$(grep $IP $HOST_FILE --color=never)
	
	sed "s#$_line#$_line	$HOSTNAME#" $HOST_FILE > $TMP_FILE
	diff_save_exit
}

case $1 in
	''|?|-h|help) error;;
	edit|-e) vim $HOST_FILE; exit;;
	add) add $@; exit;;
	*) grep -E "$1" $HOST_FILE; echo; error;;
esac