#!/usr/bin/env bash
# TODO: remove write to temp file

IP="127.0.0.1"
HOST_FILE=$(ls ~/dotfiles/etc/hosts)
TMP_FILE="/var/tmp/hosts"

[ $(uname) = "Linux" ] && sedRegExp="-r" || sedRegExp="-E"

function _error()
{
	[ $# -eq 0 ] && _usage && exit 0
	echo -e "\nError: $@"
	_usage
	exit 1
}

function _usage()
{
	echo
	echo "Usage: ${0##/*/} <add|--add|-a> hostname [127.0.0.1]"
	echo "Usage: ${0##/*/} <remove|rm|--remove|-r|-d> hostname"
	echo "Usage: ${0##/*/} <pattern> # search"
	echo "Usage: ${0##/*/} <edit|--edit|-e>"
	echo
}

# Test an IP address for validity:
# http://www.linuxjournal.com/content/validating-ip-address-bash-script
# Usage:
#      valid_ip IP_ADDRESS
#      if [[ $? -eq 0 ]]; then echo good; else echo bad; fi
#   OR
#      if valid_ip IP_ADDRESS; then echo good; else echo bad; fi
#
function valid_ip()
{
	[ $# -eq 0 ] && _error Please provide an IP address
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

function diff_save_exit()
{
	git diff --no-index $HOST_FILE $TMP_FILE
	mv $TMP_FILE $HOST_FILE
	exit
}

function _add()
{
	[ $# -le 1 ] && _error Please provide hostname
	_hostname="$2"
	IP="${3:-$IP}"
	valid_ip $IP || _error Please provide a valid IP address

	# check if hostname exist
	grep -iEq "[[:space:]]$_hostname([[:space:]]|$)" $HOST_FILE &&
		$0 $_hostname &&
		_error "Hostname exist"

	if [ $(grep -c $IP $HOST_FILE) -eq 0 ]
	then
		# IP does not exist, add new entry
		cp $HOST_FILE $TMP_FILE
		echo "$IP	$_hostname" >> $TMP_FILE
	else
		# IP exist to append new entry
		sed $sedRegExp "s#($IP[[:space:]].*\$)#\1	$_hostname#" $HOST_FILE > $TMP_FILE
	fi

	diff_save_exit
}

function _remove()
{
	[ $# -le 1 ] && _error Please provide hostname
	_hostname="$2"
	_match="[[:space:]]$_hostname([[:space:]]|$)"

	if [ $(grep -iE $_match $HOST_FILE | tr "[[:space:]]" "\n" | wc -l) -le 2 ]
	then
		sed $sedRegExp "/$_match/d" $HOST_FILE > $TMP_FILE
	else
		sed $sedRegExp "s#$_match#\1#" $HOST_FILE > $TMP_FILE
	fi

	diff_save_exit
}

case $1 in
	''|?|-h|help) _error;;
	edit|--edit|-e) vim $HOST_FILE;;
	add|--add|-a) _add $@;;
	remove|rm|--remove|-r|-d) _remove $@;;
	*) grep -E "$1" $HOST_FILE;;
esac